# frozen_string_literal: true

if respond_to?(:namespace) # cap2 differentiator
  load 'deploy'
else
  require 'capistrano/setup'
  require 'capistrano/deploy'
end

require 'capistrano/neeto-bugtrap-ruby'
