# frozen_string_literal: true

# A test harness for RakeHandler
#
require 'rake'
require 'rubygems'

# Should catch exception
task :neetobugtrap do
  stub_tty_output(false)
  require 'neeto-bugtrap-ruby'
  raise_exception
end

# Should not catch exception as tty_output is true
task :neetobugtrap_autodetect_from_terminal do
  stub_tty_output(true)
  require 'neeto-bugtrap-ruby'
  raise_exception
end

def stub_tty_output(value)
  if value
    def $stdout.tty?
      true
    end
  else
    def $stdout.tty?
      false
    end
  end
end

def raise_exception
  raise 'Jim has left the building :('
end
